"""Generate the Windows version resource for the executable.

An unsigned binary with no metadata at all looks more suspicious to endpoint
protection - and to a curious IT administrator - than one that says plainly
what it is and who produced it. The values come from :mod:`app.version` so
the resource can never drift out of step with the application.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.version import (  # noqa: E402
    APP_DESCRIPTION,
    APP_NAME,
    COMPANY_NAME,
    COPYRIGHT,
    VERSION,
    VERSION_TUPLE,
)

TEMPLATE = """# Windows version resource for {app_name}.
# Generated by tools/make_version_file.py - do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={version_tuple},
    prodvers={version_tuple},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
          StringStruct('CompanyName', '{company}'),
          StringStruct('FileDescription', '{description}'),
          StringStruct('FileVersion', '{version}'),
          StringStruct('InternalName', '{app_name}'),
          StringStruct('LegalCopyright', '{copyright}'),
          StringStruct('OriginalFilename', '{app_name}.exe'),
          StringStruct('ProductName', '{app_name}'),
          StringStruct('ProductVersion', '{version}'),
        ],
      )
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ],
)
"""


def build_version_file(destination: Path) -> Path:
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        TEMPLATE.format(
            app_name=APP_NAME,
            company=COMPANY_NAME,
            description=f"{APP_NAME} - {APP_DESCRIPTION}",
            version=VERSION,
            version_tuple=VERSION_TUPLE,
            copyright=COPYRIGHT,
        ),
        encoding="utf-8",
    )
    return destination


def main(argv: list[str] | None = None) -> int:
    import argparse

    parser = argparse.ArgumentParser(description="Build the Windows version resource.")
    parser.add_argument("--out", default="build/version_info.txt")
    args = parser.parse_args(argv)

    path = build_version_file(Path(args.out))
    print(f"Wrote {path} (version {VERSION})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
